### ISSUE TITLE
Program just turning off lights on G303 when running. (Don't have supported keyboard)

### ISSUE THREAD

**Issue by Dustmuffins** [antonpup/Logitech-CSGO#12]
Anytime I'm running csgo or keyboard preview mode, and I have any option selected for "Use X with other peripheral devices", the lights on my G303 simply turn off. I've tried updating LGS and rebooting to no avail.

When I run [the program detailed here](https://www.reddit.com/r/GlobalOffensive/comments/424bg4/logitech_csgo_game_integration_v020_with/cz8t5bt) (separately), I don't have issues with the Gamestate integration controlling my 303.

Disclaimer: I do not currently have a supported keyboard. Will the other peripherals not work unless I have one? I currently have a g410 on the way and it should be here by monday.

**Comment by antonpup** [comment]
Hmm.. I have moved onto combining my CSGO and Dota 2 implementations into one, with more features. So I plan on developing that one instead of this. But there should be no reason why peripherals don't work. Add me on steam, so I can troubleshoot this with you and I will add you to the testing team for Aurora. [http://steamcommunity.com/id/pupant/](http://steamcommunity.com/id/pupant/)

**Comment by SynfulTM** [comment]
I'm having the same issue, but with a G300s, any fixes?
