### ISSUE TITLE
Health, Ammo, Flashbang and Brunning animation work incorrect

### ISSUE THREAD

**Issue by Flecko1989** [antonpup/Logitech-CSGO#14]
Hey, 
first great work and thanks for the time and work you've put into this project.

(Sry for my english!)

Ammo Indicator
If I shoot is not running the ammo indicator down. But when I shoot at an enemy is 1/4 away when he dies, after a 2nd one i sthe half away... 3th 4th....

Health Indicator
the same at the Health indicator!

Flashbang animation dont work.
Same Burnning animation. 

Maybe i do it wrong :D but i need help.

greetings Flecko

**Comment by Cashewz** [comment]
Hi,

I'm experiencing the same issues on my G410.
Probably it has something to do with the latest firmware-update of the keyboard or CS-GO update..

Anyways.. thank you for this script. I appreciate your work.

**Comment by antonpup** [comment]
The issue is with the game. As far as I know, about a month ago, Valve released an update for CSGO that made GSI events delayed and inconsistent. Although new LGS does cause an issue, but is unrelated to the events not working correctly. In LGS, disable the CSGO (and dota 2 if you're using my integration for that) integrations. And make sure to place Logitech's gsi .cfg files with mine, we used the same file names and LGS overwrites the cfg file.
