### ISSUE TITLE
Performance problems

### ISSUE THREAD

**Issue by EnricoBaivo** [antonpup/Logitech-CSGO#8]
I got the feeling that the programm causes still input lag; havey feeling if effect with other peripheral devices is checked

**Comment by antonpup** [comment]
This isn't very professional of me, but I only have G910, so I cannot really test peripheral devices. Could you troubleshoot a bit and let me know what you come up with? Feel free to add me on Steam to directly send me info instead of posting here, link to my profile is found in the About tab of the program.

Disabling all "use with peripheral" settings will disable all peripheral device updates. Input lag might happen during the bomb event and when burning with burning animation enabled.

What model of i5 do you have? If it's a dual core, then that's the problem.

**Comment by EnricoBaivo** [comment]
I5-4670 @3,4GHZ 
cant find your steam name ...

**Comment by antonpup** [comment]
There's a clickable link in the About tab that leads to my profile. Just make sure to comment on my profile, so I know who to add. I have tons of people adding me from Payday 2 and CSGO.
